pi:
    cwd: /pi-cwd
    # extensions baked into the Docker image:
    extensions:
        - /app/extensions/attach.ts

# Uncomment the platform(s) you want:

# matrix:
#     homeserver: https://athena.local
#     user: "@hades:athena"
#     token: "env:MATRIX_TOKEN"
#     storage_path: /data/matrix-bot.json

discord:
    token: "env:DISCORD_TOKEN"

security:
    allowed_users:
        - "willowsparks"    # Discord username

# cron:
#     dir: /pi-cwd/cron.d
#     default_notify: "#hades:athena"    # or Discord channel ID
